#!/bin/bash

echo "🎉 Widget Extension 已经成功添加到项目中！"
echo ""
echo "📋 最后的配置步骤："
echo ""
echo "1️⃣  打开 Xcode："
echo "    open /Users/weifu/Desktop/Weather/Weather.xcodeproj"
echo ""
echo "2️⃣  配置 App Groups（非常重要！）："
echo ""
echo "    主应用 (WeathersPro):"
echo "    • 选择 WeathersPro target"
echo "    • 点击 Signing & Capabilities 标签"
echo "    • 点击左上角 + Capability"
echo "    • 搜索并添加 'App Groups'"
echo "    • 点击 App Groups 下的 '+' 按钮"
echo "    • 输入: group.com.weiweathers.weather"
echo "    • 按回车确认"
echo ""
echo "    Widget Extension:"
echo "    • 选择 WeatherWidgetExtension target"
echo "    • 重复上述步骤"
echo "    • 选择相同的 group: group.com.weiweathers.weather"
echo ""
echo "3️⃣  配置代码签名："
echo "    • 在两个 target 中选择您的开发团队"
echo "    • 确保 'Automatically manage signing' 被勾选"
echo ""
echo "4️⃣  编译和运行："
echo "    • 选择真机或模拟器"
echo "    • 按 Cmd+B 编译"
echo "    • 按 Cmd+R 运行"
echo ""
echo "5️⃣  测试小组件："
echo "    • 在应用中获取天气数据"
echo "    • 返回主屏幕"
echo "    • 长按添加小组件"
echo ""
echo "💾 项目文件备份位置："
echo "   /Users/weifu/Desktop/Weather/Weather.xcodeproj/project.pbxproj.backup"
echo ""
echo "🚀 现在打开 Xcode 完成配置..."
sleep 2

# 尝试打开 Xcode
open /Users/weifu/Desktop/Weather/Weather.xcodeproj 2>/dev/null || echo "请手动打开 Xcode 项目"